db.url=jdbc:mysql://localhost:3306/product_catalog_db
db.username=product_catalog_user
db.password=password123
db.driver=com.mysql.cj.jdbc.Driver

hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true