caffeine.jcache {
  default {
    policy.maximum.size = 1000
    policy.expiration.time-to-live = "10m"
    monitoring.statistics = true
  }

  "category-cache" {
    policy.maximum.size = 100
    policy.expiration.time-to-live = "24h"
  }

  "category-products-cache" {
    policy.maximum.size = 500
    policy.expiration.time-to-live = "1h"
  }

  "product-cache" {
    policy.maximum.size = 5000
    policy.expiration.time-to-live = "1h"
  }

 "product-natural-id-cache" {
   policy.maximum.size = 5000
   policy.expiration.time-to-live = "1h"
 }

  "default-query-results-region" {
    policy.maximum.size = 2000
    policy.expiration.time-to-live = "5m"
  }

  "default-update-timestamps-region" {
    policy.maximum.size = 5000
  }
}